modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="yourmod"
version="1.0.0"
displayName="YourMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="admin, MCreator"

[[dependencies.yourmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



